config/routes.rb
Csp::Application.routes.draw do
  resources :users do
    get :profile,:on=>:member
    get 'edit_profile', :on=>:member
    put 'update_profile', :on=>:member
    get 'change_password', :on=>:member
#    put 'update_password',:on=>:member
  end
  resources :generals

  resources :transactions  do
    post :csv_import, :on=>:collection
    post :export, :on=>:collection
    post :remove,:on=>:collection
  end

  resources :accounts  do
    post 'csv_import',:on=>:collection
    get 'export',:on=>:collection
  end

#  root :to => "accounts#index"

  resources :user_sessions

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"

  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/transactions_controller.rb
# Author: Chaitanya Ram N
# Date: 03022012
#########################################################
class TransactionsController < ApplicationController
  before_filter :recent_items
  layout "admin", :except => [:export]

  def index
    @transactions = Transaction.search(params[:search]).paginate(:page => params[:page], :per_page => 50).order("transaction_date DESC")

    render :layout => "application"

  end

  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @transaction }
    end
  end

  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @transaction }
    end
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully created.') }
        format.xml { render :xml => @transaction, :status => :created, :location => @transaction }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to(transactions_url) }
      format.xml { head :ok }
    end
  end

  def upload
  end
  def csv_import
    require 'csv'
    csv_file = params[:file]
    n=0
    CSV.new(csv_file.tempfile, :col_sep => ",").each do |row|
      transaction = Transaction.create do |tr|
        tr.csp_code =row[0]
        tr.amount = row[1]
        tr.transaction_date = params[:start_date]
      end
      transaction.save
      n = n + 1
    end
    flash[:success]= "#{n} Transactions are imported successfully"
    respond_to do |format|
      format.html { redirect_to(transactions_path) }
      format.xml { head :ok }
    end
  end

  def export
    @transactions = Transaction.where("amount <=? AND transaction_date =?", -1000, params[:date_selected].to_date)

    if params[:theme] == "pdf"    ## for PDF
      #render :layout => nil
      html = render_to_string :layout => false
      kit = PDFKit.new(html)
      send_data(kit.to_pdf, :filename => "Account_Statement_" + params[:date_selected] +".pdf", :type => 'application/pdf')
    elsif params[:theme]=="text"    ## for Text
      require 'csv'
      total = 0
      outfile = "Transaction_Report_" + Time.now.strftime("%d-%m-%Y") + ".txt"
      csv_data = CSV.generate do |csv|
        @transactions.each do |tr|
          account = Account.where(:csp_code => tr.csp_code).first
          if account.blank?
          else
            if account.account_number == 'N.A' || account.account_number == '00000000000'
            else
              amount = (-1) * tr.amount
              amount= amount % 100 == 0 ? amount : amount - (amount % 100)
              total += amount
            end
          end
        end
        csv<<[31633006672, '03607', Time.now.strftime("%d/%m/%Y"), "%.2f"%total, nil, '3A43', 'CSP Transfer']
        @transactions.each do |tr|
          account = Account.where(:csp_code => tr.csp_code).first
          if account.blank?
          else
            if account.account_number == 'N.A' || account.account_number == '00000000000'
            else
              amount = (-1) * tr.amount
              amount= amount % 100 == 0 ? amount : amount - (amount % 100)
              total += amount
              csv << [account.account_number, account.bank_code, Time.now.strftime("%d/%m/%Y"), nil, "%.2f"%amount, account.csp_code, 'CSP Transfer']
            end
          end
        end

      end
      send_data csv_data,
                :type => 'text/plain; charset=UTF-8',
                :disposition => "attachment; filename=#{outfile}"
    else     ##for EXCEL
=begin
      outfile = "Transaction_Report_" + Time.now.strftime("%d-%m-%Y") + ".xls"
      headers['Content-Type'] = "application/vnd.ms-excel"
      headers['Content-Disposition'] = "attachment; filename=#{outfile}"
      headers['Cache-Control'] = ''

      render :report_excel
=end
      book = Spreadsheet::Workbook.new
      sheet1 = book.create_worksheet
      sheet1.row(0).concat  ["SR", "KO ID", "AMOUNT", "D/W"]
      i=1
     @transactions.each do |tr|
       account = Account.where(:csp_code => tr.csp_code).first
       if account.blank?
       else
         if account.account_number == 'N.A' || account.account_number == '00000000000'
         else
           amount = (-1) * tr.amount
           amount= amount % 100 == 0 ? amount : amount - (amount % 100)

           sheet1[i,0] = i
          sheet1[i,1] = tr.csp_code
          sheet1[i,2] = amount
          sheet1[i,3] = 'W'
        i+=1
         end
       end
       end
      @outfile = "Transaction_Report_Excel_" + Time.now.strftime("%d-%m-%Y") + ".xls"

      require 'stringio'
      data = StringIO.new ''
      book.write data
      send_data data.string, :type=>"application/excel", :disposition=>'attachment', :filename => @outfile
    end
  end

  def export_form
  end

  def delete_form
  end

  def remove
    @transactions = Transaction.where(:transaction_date => params[:remove_date_selected].to_date)
    flash[:error]= "#{@transactions.size} Transactions are Removed successfully"
    @transactions.delete_all
    respond_to do |format|
      format.html { redirect_to(transactions_url) }
      format.xml { head :ok }
    end
  end
  def report_excel
    @transactions = Transaction.where("amount <=? AND transaction_date =?", -1000, params[:date_selected].to_date)

  end

  ############################
  private
  def recent_items
    @recent_transactions = Transaction.order('id DESC').limit(5)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_delete_form.html.erb
<h4>Please select the Date to Delete Transactions </h4>
<%= form_tag remove_transactions_path do  -%>
<table class="tablesorter1" align="center">

<tr>
      <td>
        <label for="vle_user">
            Select a Date :
        </label>
    </td>
    <td>
        <%= text_field_tag :remove_date_selected, Time.now.strftime('%d-%m-%Y') -%>
    </td>
</tr>
 <tr>
      <td colspan='2' align="right">
        <%= submit_tag 'Submit',:onClick=>"return confirmSubmit()" -%>
    </td>
</tr>
</table>
<% end -%>
<script>
    $(function() {
        $("#remove_date_selected").datepicker({dateFormat:'dd-mm-yy', maxDate:0 });
    });
    function confirmSubmit() {
        var agree = confirm("Are you sure to want to Remove Transactions..?");
        if (agree) {
            return true;}
        else
        {return false;}
    }
</script>
<style type="text/css">
  table.tablesorter1 {
	border-collapse: collapse;
	border: 1px solid #CDCDCD;
	text-align: center;
}
  table.tablesorter1 td, table.tablesorter1 th{
      border-collapse: collapse;
      border: 1px solid #CDCDCD;
  }

</style>

app/views/transactions/_export_form.html.erb
<h4>Please select the Date to Generate Transactions Report</h4>
<%= form_tag export_transactions_path do -%>
    <table class="tablesorter1" align="center">

      <tr>
        <td>
          <label for="vle_user">
            Select a Date :
          </label>
        </td>

        <td>
          <%= text_field_tag :date_selected, Time.now.strftime('%d-%m-%Y') -%>
        </td>
      </tr>
      <tr>
        <td>
          <label for="vle_user">
            Select a Export Format :
          </label>
        </td>

        <td>
          <%= radio_button_tag 'theme', 'pdf', true %> PDF
          <%= radio_button_tag 'theme', 'text' %> TEXT
          <%= radio_button_tag 'theme', 'excel' %> EXCEL
        </td>
      </tr>
      <tr>
        <td colspan='2' align="right">
          <%= submit_tag 'Submit' -%>
        </td>
      </tr>
    </table>
<% end -%>
<script>
    $(function () {
        $("#date_selected").datepicker({dateFormat:'dd-mm-yy', maxDate:0 });
    });
</script>
<style type="text/css">
    table.tablesorter1 {
        border-collapse: collapse;
        border: 1px solid #CDCDCD;
        text-align: center;
    }

    table.tablesorter1 td, table.tablesorter1 th {
        border-collapse: collapse;
        border: 1px solid #CDCDCD;
    }
</style>

app/views/transactions/_form.html.erb
<%= simple_form_for(@transaction) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/transactions/_recent_items.html.erb
<% for ac in  @recent_transactions %>
<li class="" id="recent_transaction_<%= ac.id%>">
    <dt>
        <%=link_to truncate(ac.csp_code,:length=>27),account_path(ac) %>
    </dt>
    <tt>
        <br/>
    </tt>
</li>
<% end %>

app/views/transactions/_upload.html.erb
<h4>Please Select the Transactions File</h4>
<%= form_tag csv_import_transactions_path, :multipart => true do -%>
    <table class="tablesorter1" align="center">
      <tr>
        <td>
          <label for="vle_user">
            Select a CSV File :
          </label>
        </td>
        <td>
          <%= file_field_tag :file, :id => "statename" -%>
          <script type="text/javascript">
              var statename = new LiveValidation('statename', {
                  onlyOnSubmit:true
              });
              statename.add(Validate.Presence)
          </script>
        </td>
      </tr>
      <tr>
        <td>
          <label for="vle_user">
            Select a Date :
          </label>
        </td>
        <td>
          <%= text_field_tag :start_date, Time.now.strftime('%d-%m-%Y') -%>
        </td>
      </tr>
      <tr>
        <td colspan='2' align="right">
          <%= submit_tag 'Submit', :disable_with => 'Please wait...' -%>
        </td>
      </tr>
    </table>
<% end -%>
<script>
    $(function () {
        $("#start_date").datepicker({dateFormat:'dd-mm-yy', maxDate:0 });
    });
</script>
<style type="text/css">
    table.tablesorter1 {
        border-collapse: collapse;
        border: 1px solid #CDCDCD;
        text-align: center;
    }

    table.tablesorter1 td, table.tablesorter1 th {
        border-collapse: collapse;
        border: 1px solid #CDCDCD;
    }

</style>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/export.html.erb
<p align="center">CSP Fund Transfer Statement of <%= params[:date_selected] %> </p>
<% total = 0 %>
<table class="tablesorter1" align="center">
  <thead>
  <tr>
    <th>SNo</th>
    <th>CSP Code</th>
    <th>Name</th>
    <th>Account</th>
    <th>Code</th>
    <th>Amount</th>
  </tr>
  </thead>
  <% i=1 %>
  <% @transactions.each do |tr| %>
      <tr align="left">
        <td><%= i %></td>
        <td><%= tr.csp_code %></td>
        <td><%= get_csp_name(tr).titleize %></td>
        <td><%= get_csp_account_number(tr) %></td>
        <!--<td><%# get_csp_branch(tr).titleize %></td>-->
        <td><%= get_csp_branch_code(tr) %></td>
        <% amount = (-1) * tr.amount %>
        <td align="right"><%= amount= amount % 100 == 0 ? amount : amount - (amount % 100) %></td>
        <% total += amount %>
      </tr>
      <% i = i + 1 %>
  <% end %>
  <tr>
    <td colspan="5" align="right">Total:</td>
    <td align="right"><%= total %></td>
  </tr>
</table>


<style type="text/css">
    table.tablesorter1 {
        border-collapse: collapse;
        border: 1px solid #000000;
        font-family: Arial, Helvetica, sans-serif;
        font-size: 14px;
    }

    table.tablesorter1 td, table.tablesorter1 th {
        border-collapse: collapse;
        border: 1px solid #000000;
    }

    p
    {
        font-family:'Bookman Old Style',Bookman,'URW Bookman L','Palatino Linotype',serif;
    }
</style>

app/views/transactions/index.html.erb
<h3>Transactions | Manage Transactions</h3>
<div class="help_text">
  * List of All CSP Transactions.<br/>
</div>
<%= link_to 'Import Transactions', "#", :class=>'more', :id=>'add_new' %>&nbsp;
<%= link_to 'Export Statement', "#", :class=>'more', :id=>'export_add' %>&nbsp;
<%= link_to 'Delete Transactions', "#", :class=>'more', :id=>'delete_add' %>&nbsp;
<div id="new_form">
  <%= render 'upload' %>
</div>
<div id="export_form">
  <%= render 'export_form' %>
</div>
<div id="delete_form">
  <%= render 'delete_form' %>
</div>
<div class="list">
  <table class="tablesorter" cellspacing="1">
    <thead>
    <tr>
      <th>SNo</th>
      <th>Date</th>
      <th>CSP Code</th>
      <th>Holding Amount</th>
    </tr>
    </thead>
    <% i=1 %>
    <% @transactions.each do |tr| %>
        <tr align="left">
          <td><%= i %></td>
          <td><%= tr.transaction_date.strftime("%d-%m-%Y") %></td>
          <td><%= highlight(tr.csp_code, params[:search]) %></td>
          <td align="right"><%= tr.amount %></td>
        </tr>
        <% i = i + 1 %>
    <% end %>
  </table>
</div>
<div class="flickr_pagination">
  <%= page_entries_info @transactions, :entry_name => 'Transactions' %> <%= will_paginate @transactions, :container => false %>
</div>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/report_excel.html.erb
<% i=1 %>
<% @transactions.each do |tr| %>
    <% account = Account.where(:csp_code => tr.csp_code).first %>
    <% if account.blank? %>
    <% else %>
        <% if account.account_number == 'N.A' || account.account_number == '00000000000' %>
        <% else %>
            <%= i %>
            <%= tr.csp_code %>
            <% amount = (-1) * tr.amount %>
            <%= amount= amount % 100 == 0 ? amount : amount - (amount % 100) %>
            W
            <% i = i + 1 %>
        <% end %>
    <% end %>
<% end %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>