config/routes.rb
Csp::Application.routes.draw do
  resources :users do
    get :profile,:on=>:member
    get 'edit_profile', :on=>:member
    put 'update_profile', :on=>:member
    get 'change_password', :on=>:member
#    put 'update_password',:on=>:member
  end
  resources :generals

  resources :transactions  do
    post :csv_import, :on=>:collection
    post :export, :on=>:collection
    post :remove,:on=>:collection
  end

  resources :accounts  do
    post 'csv_import',:on=>:collection
    get 'export',:on=>:collection
  end

#  root :to => "accounts#index"

  resources :user_sessions

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"

  match ':controller(/:action(/:id(.:format)))'
end

app/views/common/_footer.html.erb
<div class="copyright_text">
    <div>
      ©     <%= Time.now.strftime('%Y') %>
  <a href="http://vedavaag.com" target="_blank">Vedavaag</a> Systems Limited. This is site is optimized to Firefox, Google Chrome and IE8+ Versions.
    </div>
</div>

app/views/common/_header.html.erb
  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8"/>
    <title>SBI-KIOSK</title>
    <%= stylesheet_link_tag 'style','admin_screen','common','jquery-ui-1.8.13.custom','live_validation' %>
    <%= javascript_include_tag :defaults,'rails.validations.js','jquery-ui-1.8.13.custom.min','livevalidation_standalone.compressed' %>
    <%= csrf_meta_tag %>
  </head>
  <body>
  <div id="page_container">
    <div id="page_top">
      <a href="#"><%= image_tag("/images/logo.png", :size => "300x40", :alt => "Home") %></a>

      <div id="top_menu">
        <div id="top_m">

          <ul class="top_menu">
            <li>
              Welcome, <%= current_user.name %> !
            </li>
            <li>
              <%= link_to 'Home', {:controller=>'generals', :action=>'index'} %>
            </li>
            <li>
              <%= link_to 'Profile', {:controller=>'users', :action=>'profile', :id=>current_user.id}, :class=>"tipTip2", :title=>"Update Profile" %>
            </li>
            <li>

              <%=link_to 'Logoff', logout_path, :id=>"logoff", :class=>"tipTip2", :title=>"Logoff" %>
            </li>
          </ul>

        </div>
      </div>
    </div>

app/views/common/_import_flash.html.erb
<%flash.each do |name, msg| %>
<%= content_tag :div, msg, :id => "flash_#{name}",:class =>"flash_#{name}" %>
<%end %>

app/views/common/_menu.html.erb
<div id="page_menu">
<ul class="page_menu">

  <li>
    <a href="#">
      <div class="menu-l">
        &nbsp;
      </div>
      <div class="menu-c">
        <span>&nbsp;&nbsp;GENERAL&nbsp;&nbsp;&nbsp;</span>
      </div>
      <div class="menu-r">
        &nbsp;
      </div>
    </a>
    <ul>
      <li>
        <%= link_to 'Users', users_path,:class=>"tipTip1",:title=>"Manage States" %>
      </li>
    </ul>
  </li>
  <li>
    <a href="#">
      <div class="menu-l">
        &nbsp;
      </div>
      <div class="menu-c">
        <span>&nbsp;&nbsp;ACCOUNTS&nbsp;&nbsp;&nbsp;</span>
      </div>
      <div class="menu-r">
        &nbsp;
      </div>
    </a>
    <ul>
      <li>
        <%= link_to 'Manage Accounts', accounts_path %>
      </li>
    </ul>
  </li>
  <li>
    <a href="#">
      <div class="menu-l">
        &nbsp;
      </div>
      <div class="menu-c">
        <span>&nbsp;&nbsp;TRANSACTIONS&nbsp;&nbsp;&nbsp;</span>
      </div>
      <div class="menu-r">
        &nbsp;
      </div>
    </a>
    <ul>
      <li>
        <%= link_to 'Manage Transactions', transactions_path %>
      </li>
    </ul>
  </li>
</ul>
</div>

app/views/common/_search.html.erb
<div class="like" style="">
    <div class="margin">
        <h3>Search</h3>
        <%= hidden_field_tag :direction, params[:direction] %>
        <%= hidden_field_tag :sort, params[:sort] %>
        <div class="searchbox">
            <%= form_tag(controller_name, :method => 'get') do %>
            <%= text_field_tag :search, params[:search],:size=>15, :class => "formTextBox" %>
            <%= submit_tag 'Go', :disable_with=>'...'%>
            <% end %>
        </div>
    </div>
</div>