config/routes.rb
Csp::Application.routes.draw do
  resources :users do
    get :profile,:on=>:member
    get 'edit_profile', :on=>:member
    put 'update_profile', :on=>:member
    get 'change_password', :on=>:member
#    put 'update_password',:on=>:member
  end
  resources :generals

  resources :transactions  do
    post :csv_import, :on=>:collection
    post :export, :on=>:collection
    post :remove,:on=>:collection
  end

  resources :accounts  do
    post 'csv_import',:on=>:collection
    get 'export',:on=>:collection
  end

#  root :to => "accounts#index"

  resources :user_sessions

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/account.rb
class Account < ActiveRecord::Base

  #validations
  validates :name, :presence => true, :length => { :maximum => 200}
  validates :csp_code, :presence => true, :uniqueness => true, :length => { :maximum => 20}

  #Search - Meta Where
    def self.search(search)
    if search
      where({:name.matches => "%#{search}%"} | {:csp_code.matches => "%#{search}%"})
    else
      scoped
    end
  end
end

app/controllers/accounts_controller.rb
# Author: Chaitanya Ram
# Controller: Accounts
# Date: 03022012
######################################################
require 'csv'
class AccountsController < ApplicationController
  layout "admin"
  before_filter :recent_items

  def index
    @accounts = Account.search(params[:search]).paginate(:page => params[:page], :per_page => 20).order('csp_code ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @accounts }
    end
  end

  def show
    @account = Account.find(params[:id])
    render :layout => "application"
  end

  def new
    @account = Account.new
    render :layout => "application"

  end

  def edit
    @account = Account.find(params[:id])
    render :layout => "application"
  end

  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to(@account, :notice => 'Account was successfully created.') }
        format.xml { render :xml => @account, :status => :created, :location => @account }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to(@account, :notice => 'Account was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to(accounts_url) }
      format.xml { head :ok }
    end
  end

  def upload

  end

  def csv_import
    csv_file = params[:file]
    n=0
    CSV.new(csv_file.tempfile, :col_sep => ",").each do |row|
      account = Account.create do |acc|
        acc.name =row[0]
        acc.csp_code = row[1]
        acc.mobile = row[2]
        acc.district = row[3]
        acc.bank_branch = row[4]
        acc.bank_code = row[5]
        acc.account_number = row[6]
        acc.bank_name= "SBI"
      end
      account.save
      n = n + 1
    end
    flash[:notice]= "#{n} Accounts are imported successfully"
    respond_to do |format|
      format.html { redirect_to(accounts_path) }
      format.xml { head :ok }
    end
  end

  def export
    @accounts = Account.all
    html = render_to_string :layout => false
    kit = PDFKit.new(html, :page_size => 'A4')
    send_data(kit.to_pdf, :filename => "Account_Statement.pdf", :type => 'application/pdf')

  end

############################
  private
  def recent_items
    @recent_accounts = Account.order('id DESC').limit(5)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= simple_form_for(@account, :validate => true) do |f| %>
      <fieldset>
        <%= f.input :name, :label => 'Enter Name of CSP', :placeholder => "CSP Name" %>
        <%= f.input :csp_code, :label => 'Enter CSP Code', :placeholder => "3A430000" %>
        <%= f.input :mobile, :label => 'Enter Mobile Number', :placeholder => "Ex:9292929292" %>
        <%= f.input :bank_name, :label => 'Enter Bank Name', :input_html => {:value => 'SBI'} %>
        <%= f.input :bank_branch, :label => "Enter Branch Name",:input_html => {:value => 'N.A'} %>
        <%= f.input :bank_code, :label => "Enter Branch Code",:input_html => {:value => '00000'} %>
        <%= f.input :account_number, :label => "Enter Account Number",:input_html => {:value => '00000000000'}%>
        <%= f.submit 'Save', :disable_with => 'Please wait...' %>
      </fieldset>
  <% end %>
</div>

app/views/accounts/_recent_items.html.erb
<% for ac in  @recent_accounts %>
<li class="" id="recent_account_<%= ac.id%>">
    <dt>
        <%=link_to truncate(ac.name.titleize,:length=>20),account_path(ac) %>
    </dt>
    <tt>
        <br/>
    </tt>
</li>
<% end %>

app/views/accounts/_upload.html.erb
<h4>Please Select the Transactions File</h4>
<%= form_tag csv_import_accounts_path, :multipart => true do  -%>
<table class="tablesorter1" align="center">
<tr>
    <td>
        <label for="vle_user">
            Select a CSV File :
        </label>
    </td>
    <td>
        <%= file_field_tag :file,:id=>"statename" -%>
                  <script type="text/javascript">
                var statename = new LiveValidation('statename', {
                    onlyOnSubmit: true
                });
                statename.add(Validate.Presence)
            </script>
    </td>
</tr>
 <tr>
      <td colspan='2' align="right">
        <%= submit_tag 'Submit' ,:disable_with=>'Please wait...'-%>
    </td>
</tr>
</table>
<% end -%>
<style type="text/css">
  table.tablesorter1 {
	border-collapse: collapse;
	border: 1px solid #CDCDCD;
	text-align: center;
}
  table.tablesorter1 td, table.tablesorter1 th{
      border-collapse: collapse;
      border: 1px solid #CDCDCD;
  }

</style>

app/views/accounts/edit.html.erb
<h3>Accounts | Edit Account</h3>
<div class="list">
  <div class="help_text">
    * Edit the below form for Account.<br/>* Please check all entries before Save.
  </div>
<%# render 'form' %>
  <div class="form-container">
    <p class="legend">
      <strong>Note:</strong>
      Required fields are marked with an asterisk (<em>*</em>)
    </p>
    <%= simple_form_for(@account, :validate => true) do |f| %>
        <fieldset>
          <%= f.input :name, :label => 'Enter Name of CSP', :placeholder => "CSP Name" %>
          <%= f.input :csp_code, :label => 'Enter CSP Code', :placeholder => "3A430000" %>
          <%= f.input :mobile, :label => 'Enter Mobile Number', :placeholder => "Ex:9292929292" %>
          <%= f.input :bank_name, :label => 'Enter Bank Name', :input_html => {:value => 'SBI'} %>
          <%= f.input :bank_branch, :label => "Enter Branch Name" %>
          <%= f.input :bank_code, :label => "Enter Branch Code" %>
          <%= f.input :account_number, :label => "Enter Account Number"%>
          <%= f.submit 'Save', :disable_with => 'Please wait...' %>
        </fieldset>
    <% end %>
  </div>
<%= link_to 'Show', @account, :class=>"more" %> &nbsp;
<%= link_to 'Back to Accounts', accounts_path,:class=>"more" %>
</div>

app/views/accounts/export.html.erb
<table class="tablesorter">
  <thead>
  <tr>
    <th>SNo</th>
    <th>CSP Code</th>
    <th>Name</th>
    <th>District</th>
    <th>Account No</th>
    <th>Branch</th>
  </tr>
  </thead>
  <% i=1 %>
  <% @accounts.each do |tr| %>
      <tr align="left">
        <td><%= i %></td>
        <td><%= tr.csp_code %></td>
        <td><%= tr.name %></td>
        <td><%= tr.district %></td>
        <td><%= tr.account_number %></td>
        <td><%= tr.bank_branch %></td>
      </tr>
      <% i = i + 1 %>
  <% end %>
</table>

<style type="text/css">
    table.tablesorter {
        border-collapse: collapse;
        border: 1px solid #000000;
        font-size: 10px;

    }

    table.tablesorter td, table.tablesorter th {
        border-collapse: collapse;
        border: 1px solid #000000;
    }

</style>

app/views/accounts/index.html.erb
<h3>Accounts | Manage Accounts</h3>
<div class="help_text">
  * List of All CSP Accounts.
</div>
<%= link_to 'New Account', {:action => :new}, :class=>'more' %>&nbsp;
<%= link_to 'Import Accounts', "#", :class=>'more ', :id=>'add_new' %>&nbsp;
<%= link_to 'Export Accounts', {:action=>:export}, :class=>'more ' %>
<%# link_to 'Transactions', transactions_path, :class=>'more' %>

<div id="new_form">
  <%= render 'upload' %>
</div>

<div class="list">
  <table class="tablesorter" cellspacing="1">
    <thead>
    <tr>
      <th>SNo</th>
      <th>CSP Operator</th>
      <th>CSP Code</th>
      <th>Phone</th>
      <th>District</th>
      <th>Bank</th>
      <th>Branch</th>
      <th>Branch Code</th>
      <th>Account No</th>
      <th>Actions</th>
    </tr>
    </thead>
    <% i=1 %>
    <% @accounts.each do |account| %>
        <tr align="left">
          <td><%= i %></td>
          <td><%= link_to highlight(account.name.titleize, params[:search]), account, :class => "link" %></td>
          <td align="center"><%= highlight(account.csp_code, params[:search]) %></td>
          <td><%= account.mobile %></td>
          <td>
            <% if account.district? %>
                <%= account.district.titleize %>
            <% else %>
            <% end %>
          </td>
          <td><%= account.bank_name %></td>
          <td>
            <% if account.bank_branch? %>
                <%= account.bank_branch.titleize %>
            <% else %>
            <% end %>
          </td>
          <td><%= account.bank_code %></td>
          <td><%= account.account_number %></td>
          <td align="center"><%= link_to "Edit", edit_account_path(account) %></td>
        </tr>
        <% i = i + 1 %>
    <% end %>
  </table>
</div>
<div class="flickr_pagination">
  <%= page_entries_info @accounts, :entry_name => 'Accounts' %> <%= will_paginate @accounts, :container => false %>
</div>

app/views/accounts/new.html.erb
<h3>Accounts | New CSP Account Creation</h3>
<div class="list">
  <div class="help_text">
    * Fill the below form for New CSP Account.<br/>* Please check all entries before Save.
  </div>
  <%= render 'form' %>
  <%= link_to 'Back to Accounts', accounts_path, :class=>'more tipTip1',:title => "Back to States" %>
</div>

app/views/accounts/show.html.erb
<h3>Accounts | View Account Details</h3>
<div class="formbox">
  <div class="desc">CSP Code : <%= @account.csp_code %></div>
  <div class="divider"></div>
  <div class="desc">CSP Name : <%= @account.name.titleize %></div>
  <div class="divider"></div>
  <div class="desc">Phone : <%= @account.mobile %></div>
  <div class="divider"></div>
  <div class="desc">District :
    <% if @account.district? %>
        <%= @account.district.titleize %>
    <% else %>
    <% end %>
  </div>
  <div class="divider"></div>
  <div class="desc">Bank : <%= @account.bank_name %></div>
  <div class="divider"></div>
  <div class="desc">Branch :
    <% if @account.bank_branch? %>
        <%= @account.bank_branch.titleize %>
    <% else %>
    <% end %>
  </div>
  <div class="divider"></div>
  <div class="desc">Branch Code : <%= @account.bank_code %></div>
  <div class="divider"></div>
  <div class="desc">Account Number : <%= @account.account_number %></div>
  <div class="divider"></div>
</div>
<div class="bottom_links">
  <%= link_to 'Edit', edit_account_path(@account), :class=>"more" %>
  <%= link_to 'Back to Accounts', accounts_path, :class=>"more", %>
</div>